In [1]:
import os
import pandas as pd
import numpy as np

import plotly.express as px

In [2]:
# Check current working dir.
os.getcwd()

'c:\\PythonProject\\EDA-Project\\Python'

In [3]:
# Set working dir to main working dir.
os.chdir("c:\\PythonProject\\EDA-Project")
os.getcwd()

'c:\\PythonProject\\EDA-Project'

In [4]:
# Raw data file path
str_raw_data_path = "./data/sKor_raw_data.xlsx"

In [5]:
# Import raw data for household characters from excel file
df_raw_hh = pd.read_excel(str_raw_data_path, sheet_name= "household")

In [6]:
# Check raw dataframe.
df_raw_hh.head(10)

id_hh         id_hs  cat_loc_div  cat_sz_cty  cat_hus_typ  num_flr  \
0  HH13110253  HS1101000001           11           1            3        9   
1  HH14110055  HS1101000004           11           1            2        1   
2  HH13110254  HS1101000005           11           1            1        2   
3  HH14110057  HS1101000007           11           1            1        1   
4  HH17110001  HS1101000009           11           1            1        1   
5  HH18110236  HS1101000011           11           1            2        3   
6  HH18110122  HS1101000012           11           1            1        1   
7  HH18110119  HS1101000013           11           1            1        1   
8  HH13110255  HS1102000001           11           1            2        2   
9  HH11110023  HS1102000003           11           1            1        1   

   num_out_wls  cat_hus_dir_fce  num_hus_blt_yr  num_hus_ar  ...  num_bat  \
0            2                3            1995       125.4  ...        2   
1            5                1            1989       158.4  ...        1   
2            6                5            1979       264.0  ...        3   
3            5                5            1989        62.7  ...        1   
4            4                5            2012       132.0  ...        2   
5            4                5            2005        99.0  ...        2   
6            5                5            1989       112.2  ...        2   
7            4                3            1985        99.0  ...        2   
8            5                5            1990        99.0  ...        1   
9            6                3            1971       122.1  ...        2   

   num_out_wds  cat_fuel_heat  cat_cool  cat_fuel_cook  cat_sol_pv  \
0           14              5         3              5           2   
1           15              5         3              5           2   
2           20              5         3              5           2   
3           10              5         3              5           2   
4           11              5         3              5           2   
5           14              5         3              5           2   
6           16              5         3              5           2   
7           14              5         3              5           2   
8           10              5         3              5           2   
9            8              5         3              5           2   

   num_hus_mems  cat_mhh_age  cat_mhh_occu  cat_hh_ann_incm  
0             5            6             1                6  
1             4            7             1                3  
2             5            6             1                6  
3             1            7             5                3  
4             3            5             5                5  
5             3            6             1                4  
6             4            7             1                7  
7             2            9             5                3  
8             4            7             1                7  
9             5            7             3                2  

[10 rows x 22 columns]

In [7]:
# Check data types for dataframe.
df_raw_hh.dtypes

id_hh               object
id_hs               object
cat_loc_div          int64
cat_sz_cty           int64
cat_hus_typ          int64
num_flr              int64
num_out_wls          int64
cat_hus_dir_fce      int64
num_hus_blt_yr       int64
num_hus_ar         float64
num_bed              int64
num_liv              int64
num_bat              int64
num_out_wds          int64
cat_fuel_heat        int64
cat_cool             int64
cat_fuel_cook        int64
cat_sol_pv           int64
num_hus_mems         int64
cat_mhh_age          int64
cat_mhh_occu         int64
cat_hh_ann_incm      int64
dtype: object

In [8]:
# Check any NAs.
df_raw_hh.isna().sum()

id_hh              0
id_hs              0
cat_loc_div        0
cat_sz_cty         0
cat_hus_typ        0
num_flr            0
num_out_wls        0
cat_hus_dir_fce    0
num_hus_blt_yr     0
num_hus_ar         0
num_bed            0
num_liv            0
num_bat            0
num_out_wds        0
cat_fuel_heat      0
cat_cool           0
cat_fuel_cook      0
cat_sol_pv         0
num_hus_mems       0
cat_mhh_age        0
cat_mhh_occu       0
cat_hh_ann_incm    0
dtype: int64

In [9]:
# Check any negative values for not valid responses.
df_raw_hh.iloc[:,2:].lt(0).sum()

cat_loc_div        0
cat_sz_cty         0
cat_hus_typ        0
num_flr            0
num_out_wls        0
cat_hus_dir_fce    0
num_hus_blt_yr     0
num_hus_ar         0
num_bed            0
num_liv            0
num_bat            0
num_out_wds        0
cat_fuel_heat      0
cat_cool           0
cat_fuel_cook      0
cat_sol_pv         0
num_hus_mems       0
cat_mhh_age        0
cat_mhh_occu       0
cat_hh_ann_incm    0
dtype: int64

In [10]:
# Check uniqueness of household_id and house_id.
df_raw_hh_ids = df_raw_hh[["id_hh", "id_hs"]]
print(df_raw_hh_ids.duplicated(subset= "id_hh").sum())
print(df_raw_hh_ids.duplicated(subset= "id_hs").sum())

0
0


In [11]:
# Function to reduce categories for cat_loc_div.
def reduce_cat_loc_div(x):
    
    # List of codes for lumped groups
    lst_tmp_high_lat = [11, 23, 31, 32]
    lst_tmp_mid_lat = [25, 29, 33, 34, 37]
    lst_tmp_low_lat = [21, 22, 24, 26, 35, 36, 38, 39]
    
    # Conditional output
    if x in lst_tmp_high_lat:
        return 1
    elif x in lst_tmp_mid_lat:
        return 2
    elif x in lst_tmp_low_lat:
        return 3
    else:
        return -10

In [12]:
# Create new colums for reduced cat_loc_div and check.
df_raw_hh["cat_loc_div_cor"] = df_raw_hh["cat_loc_div"].apply(reduce_cat_loc_div)
df_raw_hh[["cat_loc_div","cat_loc_div_cor"]].groupby("cat_loc_div").agg(
    {
        "cat_loc_div_cor" : ["min", "max", "mean"],
    }
)

cat_loc_div_cor         
                        min max mean
cat_loc_div                         
11                        1   1    1
21                        3   3    3
22                        3   3    3
23                        1   1    1
24                        3   3    3
25                        2   2    2
26                        3   3    3
29                        2   2    2
31                        1   1    1
32                        1   1    1
33                        2   2    2
34                        2   2    2
35                        3   3    3
36                        3   3    3
37                        2   2    2
38                        3   3    3
39                        3   3    3

In [13]:
# Replace old cat_loc_div with new one cat_loc_div_cor and delete cat_loc_div_cor.
df_raw_hh["cat_loc_div"] = df_raw_hh["cat_loc_div"].apply(reduce_cat_loc_div)
df_raw_hh.drop(columns= ["cat_loc_div_cor"], inplace= True)
df_raw_hh["cat_loc_div"].unique()

array([1, 3, 2], dtype=int64)

In [14]:
# Function to reduce cat_sz_cty.
def reduce_cat_sz_cty(x):
    
    lst_tmp_metro = [1,2]
    
    if x in lst_tmp_metro:
        return 1
    elif x == 3:
        return 2
    else:
        return 2

In [15]:
# Create new colums for reduced cat_sz_cty and check.
df_raw_hh["cat_sz_cty_cor"] = df_raw_hh["cat_sz_cty"].apply(reduce_cat_sz_cty)
df_raw_hh[["cat_sz_cty","cat_sz_cty_cor"]].groupby("cat_sz_cty").agg(
    {
        "cat_sz_cty_cor" : ["min", "max", "mean"],
    }
)

cat_sz_cty_cor         
                      min max mean
cat_sz_cty                        
1                       1   1    1
2                       1   1    1
3                       2   2    2

In [16]:
# Replace old cat_sz_cty with new one cat_sz_cty_cor and delete cat_sz_cty_cor.
df_raw_hh["cat_sz_cty"] = df_raw_hh["cat_sz_cty"].apply(reduce_cat_sz_cty)
df_raw_hh.drop(columns= ["cat_sz_cty_cor"], inplace= True)
df_raw_hh["cat_sz_cty"].unique()

array([1, 2], dtype=int64)

In [17]:
# Check distribution of cat_hus_dir_fce.
fig_tmp = px.histogram(df_raw_hh, x= "cat_hus_dir_fce", title= "cat_hus_dir_fce")
fig_tmp.show()

In [18]:
# Fuction to reduce categories and reorder number with frequency.

def reduce_cat_hus_dir_fce(x):
    if x == 3:
        return 1
    elif x == 5:
        return 2
    elif x == 1:
        return 3
    elif x == 6:
        return 4
    else:
        return 5

In [19]:
# Create new colums for reduced cat_hus_dir_fce and check.
df_raw_hh["cat_hus_dir_fce_cor"] = df_raw_hh["cat_hus_dir_fce"].apply(reduce_cat_hus_dir_fce)
df_raw_hh[["cat_hus_dir_fce","cat_hus_dir_fce_cor"]].groupby("cat_hus_dir_fce").agg(
    {
        "cat_hus_dir_fce_cor" : ["min", "max", "mean"],
    }
)

cat_hus_dir_fce_cor         
                                min max mean
cat_hus_dir_fce                             
1                                 3   3    3
2                                 5   5    5
3                                 1   1    1
4                                 5   5    5
5                                 2   2    2
6                                 4   4    4
7                                 5   5    5
8                                 5   5    5

In [20]:
# Replace old cat_hus_dir_fce with new one cat_hus_dir_fce_cor and delete cat_hus_dir_fce_cor.
df_raw_hh["cat_hus_dir_fce"] = df_raw_hh["cat_hus_dir_fce"].apply(reduce_cat_hus_dir_fce)
df_raw_hh.drop(columns= ["cat_hus_dir_fce_cor"], inplace= True)
df_raw_hh["cat_hus_dir_fce"].unique()

array([1, 3, 2, 4, 5], dtype=int64)

In [21]:
# Add house age column counted for 2019 same with UK NEED data.
df_raw_hh["num_hus_age"] = 2019 - df_raw_hh["num_hus_blt_yr"]
df_raw_hh[["num_hus_age", "num_hus_blt_yr"]].describe()

num_hus_age  num_hus_blt_yr
count  2520.000000     2520.000000
mean     24.322619     1994.677381
std      12.826517       12.826517
min       2.000000     1928.000000
25%      16.000000     1988.000000
50%      23.000000     1996.000000
75%      31.000000     2003.000000
max      91.000000     2017.000000

In [22]:
# Check distribution of num_liv.
fig_tmp = px.histogram(df_raw_hh, x= "num_liv", title= "num_liv")
fig_tmp.show()

In [23]:
# Number of living room is uselsee data! Drop out.
df_raw_hh.drop(columns= ["num_liv"], inplace= True)

In [24]:
# Check distribution of num_bat.
fig_tmp = px.histogram(df_raw_hh, x= "num_bat", title= "num_bat")
fig_tmp.show()

# Seems we need to deal with some extreams.

In [25]:
# Check distribution of cat_fuel_heat.
fig_tmp = px.histogram(df_raw_hh, x= "cat_fuel_heat", title= "cat_fuel_heat")
fig_tmp.show()

In [26]:
# Function to lump down cat_fuel_heat and reorder with frquency.
def reduce_cat_fuel_heat(x):
    if x == 5:
        return 1
    elif x == 2:
        return 2
    elif x == 6:
        return 3
    else:
        return 4

In [27]:
# Create new colums for reduced cat_fuel_heat and check.
df_raw_hh["cat_fuel_heat_cor"] = df_raw_hh["cat_fuel_heat"].apply(reduce_cat_fuel_heat)
df_raw_hh[["cat_fuel_heat","cat_fuel_heat_cor"]].groupby("cat_fuel_heat").agg(
    {
        "cat_fuel_heat_cor" : ["min", "max", "mean"],
    }
)

cat_fuel_heat_cor         
                            min max mean
cat_fuel_heat                           
1                             4   4    4
2                             2   2    2
4                             4   4    4
5                             1   1    1
6                             3   3    3
7                             4   4    4
8                             4   4    4
9                             4   4    4

In [28]:
# Replace old cat_fuel_heat with new one cat_fuel_heat_cor and delete cat_fuel_heat_cor.
df_raw_hh["cat_fuel_heat"] = df_raw_hh["cat_fuel_heat"].apply(reduce_cat_fuel_heat)
df_raw_hh.drop(columns= ["cat_fuel_heat_cor"], inplace= True)
df_raw_hh["cat_fuel_heat"].unique()

array([1, 3, 2, 4], dtype=int64)

In [29]:
# Check distribution of cat_cool.
fig_tmp = px.histogram(df_raw_hh, x= "cat_cool", title= "cat_cool")
fig_tmp.show()

# Seems we need to deal with extreams.

In [30]:
# Check distribution of cat_fuel_cook.
fig_tmp = px.histogram(df_raw_hh, x= "cat_fuel_cook", title= "cat_fuel_cook")
fig_tmp.show()

# Seems we need to deal with extreams.

In [31]:
# Check distribution of cat_sol_pv.
fig_tmp = px.histogram(df_raw_hh, x= "cat_sol_pv", title= "cat_sol_pv")
fig_tmp.show()

In [32]:
# Number of cat_sol_pv is uselsee data! Drop out.
df_raw_hh.drop(columns= ["cat_sol_pv"], inplace= True)

In [33]:
# Function to lump down cat_mhh_age and reorder with frquency.
def reduce_cat_mhh_age(x):
    if x in [1,2,3]:
        return 1
    elif x in [4,5,6,7]:
        return 2
    elif x in [8,9]:
        return 3
    else:
        return 3

In [34]:
# Create new colums for reduced cat_fuel_heat and check.
df_raw_hh["cat_mhh_age_cor"] = df_raw_hh["cat_mhh_age"].apply(reduce_cat_mhh_age)
df_raw_hh[["cat_mhh_age","cat_mhh_age_cor"]].groupby("cat_mhh_age").agg(
    {
        "cat_mhh_age_cor" : ["min", "max", "mean"],
    }
)

cat_mhh_age_cor         
                        min max mean
cat_mhh_age                         
3                         1   1    1
4                         2   2    2
5                         2   2    2
6                         2   2    2
7                         2   2    2
8                         3   3    3
9                         3   3    3

In [35]:
# Replace old cat_mhh_age with new one cat_mhh_age_cor and delete cat_mhh_age_cor.
df_raw_hh["cat_mhh_age"] = df_raw_hh["cat_mhh_age"].apply(reduce_cat_mhh_age)
df_raw_hh.drop(columns= ["cat_mhh_age_cor"], inplace= True)
df_raw_hh["cat_mhh_age"].unique()

array([2, 3, 1], dtype=int64)

In [36]:
# Check distribution of cat_mhh_occu.
fig_tmp = px.histogram(df_raw_hh, x= "cat_mhh_occu", title= "cat_mhh_occu")
fig_tmp.show()

In [37]:
# Check distribution of cat_hh_ann_incm.
fig_tmp = px.histogram(df_raw_hh, x= "cat_hh_ann_incm", title= "cat_hh_ann_incm")
fig_tmp.show()

In [38]:
# Function to lumpdown annual income range... high area 7,8,9
def reduce_cat_hh_ann_incm(x):
    if x in [7,8,9]:
        return 7
    else:
        return x

In [39]:
# Create new colums for reduced cat_hh_ann_incm and check.
df_raw_hh["cat_hh_ann_incm_cor"] = df_raw_hh["cat_hh_ann_incm"].apply(reduce_cat_hh_ann_incm)
df_raw_hh[["cat_hh_ann_incm","cat_hh_ann_incm_cor"]].groupby("cat_hh_ann_incm").agg(
    {
        "cat_hh_ann_incm_cor" : ["min", "max", "mean"],
    }
)

cat_hh_ann_incm_cor         
                                min max mean
cat_hh_ann_incm                             
1                                 1   1    1
2                                 2   2    2
3                                 3   3    3
4                                 4   4    4
5                                 5   5    5
6                                 6   6    6
7                                 7   7    7
8                                 7   7    7
9                                 7   7    7

In [40]:
# Replace old cat_hh_ann_incm with new one cat_hh_ann_incm_cor and delete cat_hh_ann_incm_cor.
df_raw_hh["cat_hh_ann_incm"] = df_raw_hh["cat_hh_ann_incm"].apply(reduce_cat_hh_ann_incm)
df_raw_hh.drop(columns= ["cat_hh_ann_incm_cor"], inplace= True)
df_raw_hh["cat_hh_ann_incm"].unique()

array([6, 3, 5, 4, 7, 2, 1], dtype=int64)

In [41]:
# Import final energy consumption data.
df_raw_hh_energy = pd.read_excel(str_raw_data_path, sheet_name= "energy")
df_raw_hh_energy.head(10)

id_hs       id_hh  num_tot_energy_heat
0  HS1101000001  HH13110253         15554.885000
1  HS1101000004  HH14110055         14201.240000
2  HS1101000005  HH13110254          9864.481145
3  HS1101000007  HH14110057         13970.908639
4  HS1101000009  HH17110001          5932.097500
5  HS1101000011  HH18110236         22726.588313
6  HS1101000012  HH18110122         14151.410000
7  HS1101000013  HH18110119         13754.994557
8  HS1102000001  HH13110255          7360.518500
9  HS1102000003  HH11110023         15254.707140

In [43]:
# Check energy consumption data type.
df_raw_hh_energy.dtypes

id_hs                   object
id_hh                   object
num_tot_energy_heat    float64
dtype: object

In [44]:
# Check NA data of energy data frame.
df_raw_hh_energy.isna().sum()

id_hs                  0
id_hh                  0
num_tot_energy_heat    0
dtype: int64

In [53]:
# Check negative value in energy data frame.
df_raw_hh_energy.iloc[:,2].lt(0).sum()

0

In [54]:
# Check uniqueness of household_id and house_id.
df_raw_hh_energy_ids = df_raw_hh_energy[["id_hh", "id_hs"]]
print(df_raw_hh_energy_ids.duplicated(subset= "id_hh").sum())
print(df_raw_hh_energy_ids.duplicated(subset= "id_hs").sum())

0
0


In [ ]:
# Drop one ids column to preven merging error.
df_raw_hh_energy.drop(columns= ["id_hs"], inplace= True)

In [59]:
df_raw_hh_energy

id_hh  num_tot_energy_heat
0     HH13110253         15554.885000
1     HH14110055         14201.240000
2     HH13110254          9864.481145
3     HH14110057         13970.908639
4     HH17110001          5932.097500
...          ...                  ...
2515  HH18390009          8382.080000
2516  HH18390002         13833.220000
2517  HH18390004          7463.634620
2518  HH18390007          4644.000000
2519  HH18390008          7676.046915

[2520 rows x 2 columns]

In [61]:
# Join two dataframes
df_merged_hh_energy = pd.merge(df_raw_hh, df_raw_hh_energy, how= "inner", on= "id_hh")
df_merged_hh_energy.head(10)

id_hh         id_hs  cat_loc_div  cat_sz_cty  cat_hus_typ  num_flr  \
0  HH13110253  HS1101000001            1           1            3        9   
1  HH14110055  HS1101000004            1           1            2        1   
2  HH13110254  HS1101000005            1           1            1        2   
3  HH14110057  HS1101000007            1           1            1        1   
4  HH17110001  HS1101000009            1           1            1        1   
5  HH18110236  HS1101000011            1           1            2        3   
6  HH18110122  HS1101000012            1           1            1        1   
7  HH18110119  HS1101000013            1           1            1        1   
8  HH13110255  HS1102000001            1           1            2        2   
9  HH11110023  HS1102000003            1           1            1        1   

   num_out_wls  cat_hus_dir_fce  num_hus_blt_yr  num_hus_ar  ...  num_out_wds  \
0            2                1            1995       125.4  ...           14   
1            5                3            1989       158.4  ...           15   
2            6                2            1979       264.0  ...           20   
3            5                2            1989        62.7  ...           10   
4            4                2            2012       132.0  ...           11   
5            4                2            2005        99.0  ...           14   
6            5                2            1989       112.2  ...           16   
7            4                1            1985        99.0  ...           14   
8            5                2            1990        99.0  ...           10   
9            6                1            1971       122.1  ...            8   

   cat_fuel_heat  cat_cool  cat_fuel_cook  num_hus_mems  cat_mhh_age  \
0              1         3              5             5            2   
1              1         3              5             4            2   
2              1         3              5             5            2   
3              1         3              5             1            2   
4              1         3              5             3            2   
5              1         3              5             3            2   
6              1         3              5             4            2   
7              1         3              5             2            3   
8              1         3              5             4            2   
9              1         3              5             5            2   

   cat_mhh_occu  cat_hh_ann_incm  num_hus_age  num_tot_energy_heat  
0             1                6           24         15554.885000  
1             1                3           30         14201.240000  
2             1                6           40          9864.481145  
3             5                3           30         13970.908639  
4             5                5            7          5932.097500  
5             1                4           14         22726.588313  
6             1                7           30         14151.410000  
7             5                3           34         13754.994557  
8             1                7           29          7360.518500  
9             3                2           48         15254.707140  

[10 rows x 22 columns]

In [62]:
df_merged_hh_energy.isna().sum()

id_hh                  0
id_hs                  0
cat_loc_div            0
cat_sz_cty             0
cat_hus_typ            0
num_flr                0
num_out_wls            0
cat_hus_dir_fce        0
num_hus_blt_yr         0
num_hus_ar             0
num_bed                0
num_bat                0
num_out_wds            0
cat_fuel_heat          0
cat_cool               0
cat_fuel_cook          0
num_hus_mems           0
cat_mhh_age            0
cat_mhh_occu           0
cat_hh_ann_incm        0
num_hus_age            0
num_tot_energy_heat    0
dtype: int64

In [63]:
df_merged_hh_energy.dtypes

id_hh                   object
id_hs                   object
cat_loc_div              int64
cat_sz_cty               int64
cat_hus_typ              int64
num_flr                  int64
num_out_wls              int64
cat_hus_dir_fce          int64
num_hus_blt_yr           int64
num_hus_ar             float64
num_bed                  int64
num_bat                  int64
num_out_wds              int64
cat_fuel_heat            int64
cat_cool                 int64
cat_fuel_cook            int64
num_hus_mems             int64
cat_mhh_age              int64
cat_mhh_occu             int64
cat_hh_ann_incm          int64
num_hus_age              int64
num_tot_energy_heat    float64
dtype: object

In [64]:
df_merged_hh_energy.to_csv("./data/sKor_data_v01.csv")